### PR TITLE
Remove Shelly Wave 2PM 12.04 firmware update

### PR DESCRIPTION
**Pull request by QubinoHelp**

### CODE REVIEW

**Review by AlCalzone — APPROVED** [review]

**Comment by Pilot001** [comment]
Excuse me for disturbing, but does anybody know why this version got removed out of a sudden?

**Comment by QubinoHelp** [comment]
It is likely that the update contains a bug that occurs randomly (within 1 to 6 days). We are currently investigating this issue. Once we identify the cause, we will fix it and release a new firmware update.

**Comment by Tamas-Toth-ebola** [comment]
It's good to know that the official site does not update information from the dev resources either :disappointed: ...

https://support.shelly.cloud/en/support/solutions/articles/103000258471-shelly-qubino-wave-firmware-updates
_(latest v10.35)_

vs.

https://github.com/QubinoHelp/Shelly_Wave_FW_OTA/tree/main/Wave_2PM
_(latest v12.04)_

**Comment by Pilot001** [comment]
> It is likely that the update contains a bug that occurs randomly (within 1 to 6 days). We are currently investigating this issue. Once we identify the cause, we will fix it and release a new firmware update.

I am just wondering... wouldn't it be more open and clear to post a hint about the issue, instead of just removing everything without any trace left? What about the people who already downloaded and maybe installed the update? What is your suggestion (downgrade?)?

**Comment by QubinoHelp** [comment]
Thank you for your input. We will make sure to include information about the removal of the firmware update.

The issue is quite random and difficult to reproduce, which is why we do not have a solution yet. To prevent customers from encountering this problem, we have decided to remove the firmware update for now.

**Pull request merged**
