### PR TITLE
Add Aeotec ZWA009 and ZW100 updates

### PR DESCRIPTION
**Pull request by Aeotec-ccheng**
- Add ZWA009 V12.01 updates for older V1.X hardware
- Add ZW100 V1.17 updates for V1.14 and above

### CODE REVIEW

**Review by AlCalzone — APPROVED** [review]

**Comment by AlCalzone** [comment]
Thanks!

**Comment by Tamas-Toth-ebola** [comment]
Hi All!

Could you please help me, with why my Z-Wave JS UI does not find the corresponding update for my ZW100 device with FW v1.16?

Here is what I got on my device...

Screenshot from 2023-08-23 16-03-30

...and the process of the OTA checking...

[Screencast from 2023-08-23 16-01-40.webm](https://github.com/zwave-js/firmware-updates/assets/25765137/ca2bae8d-395b-4734-8341-dd32a6035eda)

Thanks in advance for any advice if it turns me in the right direction!

**Comment by AlCalzone** [comment]
@Tamas-Toth-ebola give it some time, this change probably hasn't propagated through all caches yet.

**Comment by Tamas-Toth-ebola** [comment]
Just for the log/note:

Until yesterday evening I still did not get the 1.17 OTA update, regularly checked through Z-Wave JS UI. 'Then', when I updated my Home Assistant - Core to 2023.8.4 - after its first start -, it showed me that there is an update for my ZW100, what process was successfully initiated from HA, and also with a successful result.

Of course, the timing was probably just a random coincidence, but was interesting for me, that I had to wait more than 24 hours to get the update after the accepted corresponding pull request.

Anyway, thanks again for all your efforts, it seems that 'everything' working fine!

**Comment by AlCalzone** [comment]
Oh right, there's also a cache in Z-Wave JS, set to 24h, to reduce the server load.

You can get around that by restarting, but I think once a day is frequent enough for most users.

**Comment by Tamas-Toth-ebola** [comment]
Do not care about me. Of course, the one day delay is more than perfect for almost everybody. Just because I realized the very new uploaded and accepted Aoetec FW-s, I was very curious about the whole Z-Wave JS based 'automatic' FW upgrade feature. The new firmwares, themselves were less interesting for me as the whole process itself, the function which offered by Z-Wave JS. As I have just EU version of Qubino and Aeotec devices, until now I could not 'test' it.

I love it, seems to be working, so do not care about the 24 hours delay, it is absolutely perfect. The only interesting part of it is that I definitely restarted the corresponding services, more times, but got the updates after the mentioned timeframe. So the service restart did not force it to check the 'upstream' hot-fresh updates. It is not a problem, I just mentioned as you wrote: `You can get around that by restarting,`

The delay in my case was approximately 1,5 days, if I take into account that you accepted the PR at ~ 16:00 _(UTC+2)_ on Wednesday and I got it at approx ~ 20:00 - 21:00 on Thursday... But it is OK! I just feared that it won't work. But as at the end was everything fine, from now I really believe in the service :smile:

_(Previously on my ZWA039 I made the upgrade manually because I thought that the brand-new update service did not work. Now I know that I just should have waited longer...)_

Thanks for everything!!!

**Pull request merged**
