### PR TITLE
Restore Inovelli LZW31-SN (draft until multi-target updates are fixed)

### PR DESCRIPTION
**Pull request by AlCalzone**
Reverts zwave-js/firmware-updates#38

### CODE REVIEW

**Comment by rohankapoorcom** [comment]
Were multi target updates fixed yet?

**Comment by AlCalzone** [comment]
Nope. I've been in contact with Inovelli a couple of times to get my hand on one of those. They wanted to send

**Comment by InovelliUSA** [comment]
> Nope. I've been in contact with Inovelli a couple of times to get my hand on one of those, so I can reproduce and fix. They wanted to send me one, but I never got it.

Hey can you email me? I'm not sure what happened, we've been working with a few different people on this issue, but I'm happy to send you one to mess with.

My email is my first name @inovelli.com

Eric

Sorry about the confusion, I'll get this out immediately.

**Comment by sdholden28** [comment]
Any eta on when this will merge?

**Comment by AlCalzone** [comment]
Honestly I'm not sure. I still need to get my hands on the device.

A while ago, Inovelli finally sent me one, only for Fedex to simply not deliver and return it to the USA without notice 🤷‍♂️

**Comment by AlCalzone** [comment]
It's fixed 🎉

I'll wait for the latest release to gain some traction, then enable these updates again.

**Comment by rohankapoorcom** [comment]
Did you finally get their switches @AlCalzone? Or did you do some magic without them?

**Comment by AlCalzone** [comment]
@sdholden28 sent me 2

**Pull request closed without merging**
