### PR TITLE
Update ZW187-A.json

### PR DESCRIPTION
**Pull request by geoffreykobrien**
added 1.6.1 from https://aeotec.freshdesk.com/helpdesk/attachments/6189341051

### CODE REVIEW

**Comment by AlCalzone** [comment]
@Aeotec-ccheng please review

**Comment by Aeotec-ccheng** [comment]
@AlCalzone its correct. I'll be updating AU/EU/US today for ZW187 as well as the MultiSensor 7 firmware versions.

**Comment by Aeotec-ccheng** [comment]
Updated all ZW187 firmwares - contained in new pull request https://github.com/zwave-js/firmware-updates/pull/147

**Comment by AlCalzone** [comment]
Thanks. Closing in favor of https://github.com/zwave-js/firmware-updates/pull/147

**Pull request closed without merging**
