### PR TITLE
Add several Zooz device firmware updates

### PR DESCRIPTION
**Pull request by uberchris2**
Since Zooz provides these updates via email and usually in a zip file, I have hosted the files that I have in a public repo.

Also, a couple of the firmware files are region dependent (US only). There is not presently a variable available to condition these updates on, so I have specified the region in the changelog.

### CODE REVIEW

**Comment by AlCalzone** [comment]
I appreciate the effort, but these updates should really be provided by the manufacturers. We do not want to get in a situation where a third party uploads possibly incorrect firmwares, but we claimed they are confirmed/provided by the manufacturer. Especially if there are limitations to what these files can be uploaded to, that we cannot currently distinguish.

I'll reach out to Zooz and leave this as a draft for now.

**Comment by uberchris2** [comment]
That's perfectly understandable.

It would probably make sense to update [the documentation](https://github.com/zwave-js/firmware-updates/blob/main/docs/firmware-files.md) to clarify that third-party contributions are not welcome.

**Comment by AlCalzone** [comment]
Good point, I've updated the readme and PR template

**Comment by mcondren** [comment]
@AlCalzone, did Zooz ever return your communication? I have all Zooz hardware and would like to get official firmware files in here.

**Comment by elaske** [comment]
Looks like they provide it with an account as well: 

> you can [access all firmware files here](https://www.support.getzooz.com/kb/article/1158-zooz-ota-firmware-files/) after you [register your product](https://www.getzooz.com/register/) and [create an account here](https://www.support.getzooz.com/?login=1). Questions? Just [reach out](https://www.support.getzooz.com/new/) to our tech support team.

**Comment by uberchris2** [comment]
> Looks like they provide it with an account as well:

I was excited to see that but it appears that these files are still served as a zip archive, which makes them unusable for this update process.

I would be happy to scrape all their firmware files off the site, decompress them, and upload them to github as I have done in this PR, but I understand the security concerns with 3rd-party firmware files.

**Comment by elaske** [comment]
I just reached out to Zooz support on this and they said they're working
with HA and ZWave JS to get them into HA soon, but weren't clear on if that
meant ZWave JS proper would get it as well and what the timeframe was.

**Comment by rhatguy** [comment]
Any update from Zooz on this lately?  I'm currently working with them on a firmware update on a Zooz switch and this (ZwaveJS repository) would be far easier than emailing back and forth with support.

**Comment by mcondren** [comment]
I was wondering about this as well. I have a bunch of switches that have updates and would love to upgrade them through zwavejs.

**Comment by kris-anderson** [comment]
It was mentioned here that Zooz only provided these via email, but they do now publicly host these for download via their website here:
[https://www.support.getzooz.com/kb/article/1158-zooz-ota-firmware-files/](https://www.support.getzooz.com/kb/article/1158-zooz-ota-firmware-files/)

**Comment by mcondren** [comment]
Hello @TSHAdmin, I see you just added firmware for the Zen04. Are you planning to add firmware for all the other Zooz devices as well? I have a bunch of light switches that I would love to update via zwavejs.

**Comment by AlCalzone** [comment]
That's the plan. We're working with Zooz to get them all on here.

**Comment by signup610** [comment]
Sorry to necro; is integrating the official Zooz firmware repo still the plan? Any low-code ways I can help? I have 75+ Zooz devices, so helping here will take less time than manually updating them. :)

**Comment by AlCalzone** [comment]
Zooz have started to provide the updates. I'll review everything when I'm back from parental next week.

**Comment by signup610** [comment]
Whatever you did: thanks! Updates are now showing in native HA for some of my ZEN72 and ZEN77 switches.

Screenshot_20240402_161252_Home Assistant

**Pull request closed without merging**
